begin;

insert into productos (id, nombre, descripcion, categoria_id, precio_usd, descuento_pct, imagen_id, reciente) values
  (1, 'Carne de Res 2da Cat troceada', 'Bolsa de 1 Kg', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 14.40, 0.00, 'tudespensa25/productos/res', false),
  (2, 'Caja de Pollo', 'caja de 40 lb de muslo y contramuslo 4 paquetes de 10 lb', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 52.00, 10.00, 'tudespensa25/productos/pollocaja', false),
  (75, 'Caja de Pollo', 'caja de 33 lb de muslo y contramuslo 3 paquetes de 11 lb', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 49.00, 10.00, 'tudespensa25/productos/caja33lbpollo', false),
  (3, 'Paquete de pollo 10 lb', 'paquete de 10 lb de muslo y contra muslo', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 13.00, 0.00, 'tudespensa25/productos/pollopqte', false),
  (77, 'Paquete de pollo 11 lb', 'paquete de 11 lb de muslo y contra muslo', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 14.00, 0.00, 'tudespensa25/productos/pollopqte', false),
  (4, 'Lomo de cerdo deshuesado', 'Lomo de cerdo Importado sellado en bolsa de 3 lb', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 12.00, 5.00, 'tudespensa25/productos/lomo', false),
  (92, 'Muslo de pollo ahumado', 'Bolsa de 3 Lb', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 7.00, 0.00, 'tudespensa25/productos/polloahumado', true),
  (93, 'Muslo de pollo ahumado', 'Bolsa de 5 Lb', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 12.00, 0.00, 'tudespensa25/productos/polloahumado', true),
  (5, 'Masas de Cerdo', 'Bandeja de masas de cerdo  sellada al vacio de 2 lb', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 7.40, 0.00, 'tudespensa25/productos/masas', true),
  (6, 'Bistec de cerdo', 'Bandeja de bistec sellada al vacio 2 lb', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 8.50, 0.00, 'tudespensa25/productos/bistec', true),
  (8, 'Jamon vicky', 'Porción de 3  lb sellado al vacio', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 9.20, 0.00, 'tudespensa25/productos/vicky', false),
  (9, 'Lomo ahumado', 'porcionado y sellado en 2.2 lb', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 12.00, 10.00, 'tudespensa25/productos/ahumado', false),
  (10, 'Lomo Ahumado', 'bandeja sellada al vacio de 1.2 lb lasqueado', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 10.20, 0.00, 'tudespensa25/productos/ahumado1', true),
  (11, 'Pechuga de pollo', 'Paquete de 2 kg', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 16.00, 0.00, 'tudespensa25/productos/pechuga', false),
  (12, 'Humaré', 'Porcion sellada al vacio de tocino + costilla ahumada', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 1.40, 0.00, 'tudespensa25/productos/humare', true),
  (134, 'Mortadela de pollo Seara', 'Tubo de 500 gr', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 2.30, 0.00, 'tudespensa25/productos/mortadela', true),
  (13, 'Picadillo de pollo', 'unidad de 400 gr', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 2.40, 20.00, 'tudespensa25/productos/picadillo', false),
  (14, 'Salchichas', 'paquete de 12 unidades', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 1.90, 0.00, 'tudespensa25/productos/perritos', false),
  (131, 'Salchichas GuiBon', 'paquete de 60 unidades (3 Kg)', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 10.90, 0.00, 'tudespensa25/productos/60uds', false),
  (132, 'Higado de Pollo', 'paquete de 1 Kg', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 3.10, 0.00, 'tudespensa25/productos/higado', false),
  (133, 'pierna de Cerdo', 'pierna entre 17 y 20 lb', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 55.00, 0.00, 'tudespensa25/productos/pierna', false),
  (15, 'Chorizo Tipo vela', 'x lb porcion sellada segun pedido del cliente', (select id from categorias where nombre = 'Alimentos/Cárnicos'), 3.20, 0.00, null, false),
  (16, 'Atún', 'Lata de 1 Kg en aceite', (select id from categorias where nombre = 'Enlatados y conservas'), 13.00, 0.00, 'tudespensa25/productos/atun', false),
  (101, 'Combo Mixto 1', 'Bolsa de 10 lb de pollo, 2 pomos de 500 ml de aceite de girasol, 1 pomo de 1,5 L de Refresco de Naranja', (select id from categorias where nombre = 'Combos Variados'), 18.50, 0.00, 'tudespensa25/productos/combopolloaceiterefresco', true),
  (153, 'Combo Mixto 2', 'Combo especial 1 kg de leche en polvo 1 L de yogurt probiótico de fresa, 500 g de espaguetis, 1 lata de garbanzo con chorizo, 30 huevos y 1 paquete de café Expreso', (select id from categorias where nombre = 'Combos Variados'), 30.99, 0.00, 'tudespensa25/productos/mixto2', true),
  (154, 'Combo Mixto 3', 'Combo especial 1 kg de Leche en polvo, 2 bolsas de Hamburguesas mixtas (5 uds c/u), 2 pomos de Aceite de girasol 500 ml, 2 unidades de Picadillo de pollo 400 g, 2 paquetes de Salchichas (10 uds c/u), 1 lata de Leche condensada, 1 paquete de Galletas María Bauducco, 2 cajitas de Gelatina.', (select id from categorias where nombre = 'Combos Variados'), 24.99, 0.00, 'tudespensa25/productos/mixto3', true),
  (17, 'Cerveza Cristal', 'Caja de 24 uds', (select id from categorias where nombre = 'Alimentos/Líquidos'), 22.00, 0.00, 'tudespensa25/productos/cristal', false),
  (129, 'Whisky Old Star', 'Botella de 1 Lts', (select id from categorias where nombre = 'Licoreria'), 5.80, 0.00, 'tudespensa25/productos/old', true),
  (18, 'Cerveza Bucanero', 'Caja de 24 uds', (select id from categorias where nombre = 'Alimentos/Líquidos'), 22.00, 0.00, 'tudespensa25/productos/bucanero', false),
  (19, 'Cerveza Economica', 'Caja de 24 uds', (select id from categorias where nombre = 'Alimentos/Líquidos'), 16.00, 0.00, 'tudespensa25/productos/timber', false),
  (20, 'Vino Acantus', 'Botella de vino rosado, tinto o Blanco', (select id from categorias where nombre = 'Licoreria'), 5.00, 0.00, 'tudespensa25/productos/acantus', false),
  (21, 'Vino Espumoso', 'botella de vino espumoso Varons d Valls 750 ml', (select id from categorias where nombre = 'Licoreria'), 10.00, 0.00, 'tudespensa25/productos/espumoso', false),
  (22, 'Ron Habana Club', 'Añejo 3 años 750 ml', (select id from categorias where nombre = 'Licoreria'), 7.70, 0.00, 'tudespensa25/productos/3anos', false),
  (23, 'Malta Guajira', 'Blister de 6 uds de 500 ml', (select id from categorias where nombre = 'Alimentos/Líquidos'), 6.50, 0.00, 'tudespensa25/productos/guajira', false),
  (24, 'Jugo', 'Caja de 24 uds de 200 ml', (select id from categorias where nombre = 'Alimentos/Líquidos'), 14.40, 0.00, 'tudespensa25/productos/200ml', false),
  (25, 'Jugo', 'Jugo La estancia Sabor Naranja 1 L', (select id from categorias where nombre = 'Alimentos/Líquidos'), 1.60, 0.00, 'tudespensa25/productos/naranja', false),
  (149, 'Jugo Goliat', 'Jugo Goliat 1  L', (select id from categorias where nombre = 'Alimentos/Líquidos'), 1.95, 0.00, 'tudespensa25/productos/peragoliat', true),
  (26, 'Jugo', 'Blister de 6 uds 330 ml Multifrutas de lata', (select id from categorias where nombre = 'Alimentos/Líquidos'), 6.50, 0.00, 'tudespensa25/productos/multifrutas', false),
  (27, 'Malta Morena', 'Caja de 24 uds', (select id from categorias where nombre = 'Alimentos/Líquidos'), 18.00, 10.00, 'tudespensa25/productos/morena', false),
  (28, 'Refresco', 'Lata 330 ml', (select id from categorias where nombre = 'Alimentos/Líquidos'), 0.55, 0.00, 'tudespensa25/productos/cintracola', false);

commit;