begin;

insert into productos (id, nombre, descripcion, categoria_id, precio_usd, descuento_pct, imagen_id, reciente) values
  (106, 'Lavadora semiautomática 9 L', 'Lavadora semiautomatica 7 L', (select id from categorias where nombre = 'De Electrodomésticos'), 320.00, 0.00, 'tudespensa25/productos/semiautomatica7', false),
  (63, 'Split milexus', 'Milexus 1200 btu', (select id from categorias where nombre = 'De Electrodomésticos'), 380.00, 0.00, 'tudespensa25/productos/split', false),
  (64, 'Frezeer', 'Milexus 6 pies', (select id from categorias where nombre = 'De Electrodomésticos'), 349.00, 0.00, 'tudespensa25/productos/freezer6p', false),
  (150, 'Frezeer', 'Milexus 4.2 pies', (select id from categorias where nombre = 'De Electrodomésticos'), 319.00, 0.00, 'tudespensa25/productos/freezer4p', false),
  (65, 'Tv de 32', 'Tv inteligente 32 pulgadas', (select id from categorias where nombre = 'De Electrodomésticos'), 260.00, 0.00, 'tudespensa25/productos/32', false),
  (66, 'Tv de 55', 'Tv inteligente Milexus 55 pulgadas', (select id from categorias where nombre = 'De Electrodomésticos'), 450.00, 0.00, 'tudespensa25/productos/55', false),
  (67, 'Batidora Milexus', 'Batidora 1.5 Lt vaso de cristal', (select id from categorias where nombre = 'De Electrodomésticos'), 45.00, 0.00, 'tudespensa25/productos/batidora', false),
  (68, 'Generador Eléctrico de Gasolina', 'Generador Eléctrico de Gasolina de 3000 w, salida de 220v y 110 v Voltaje 110-220V (50/60Hz), motor de 7.0 HP OHV TOTAL, sistema AVR para voltaje estable y panel de control súper fácil de usar. ⛽ Gran tanque de combustible con filtro, encendido por cuerda y breaker de seguridad para máxima protección. 🛠 Incluye interruptor automático AC y sistema de enfriamiento.', (select id from categorias where nombre = 'De Electrodomésticos'), 800.00, 0.00, 'tudespensa25/productos/tota', false),
  (69, 'Galletas María Baduco', 'Tubo de 170 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 1.25, 0.00, 'tudespensa25/productos/mariasbaduco', true),
  (118, 'Galletas Samyeli', 'Tubo de 150 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 0.90, 0.00, 'tudespensa25/productos/samyeli', true),
  (119, 'Donut Brawo de Caramelo', 'paquetico de 40 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 0.50, 0.00, 'tudespensa25/productos/donutbravo', true),
  (120, 'Galletas Maxi 2000', 'paquete  de 500 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 2.60, 0.00, 'tudespensa25/productos/maxis2000', true),
  (121, 'Bombom Truffle de Chocolate', 'Bolsa de 35 uds', (select id from categorias where nombre = 'Alimentos/Del Confi'), 8.60, 0.00, 'tudespensa25/productos/trufle', true),
  (122, 'Galletas black out', 'Bolsa de 4 paquetes', (select id from categorias where nombre = 'Alimentos/Del Confi'), 2.20, 0.00, 'tudespensa25/productos/blackout', true),
  (123, 'Papas Fritas Sabrosísimo', 'tubo de 140 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 2.20, 0.00, 'tudespensa25/productos/papasfritas', true),
  (124, 'Schoco cake', 'donut de 40 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 0.55, 0.00, 'tudespensa25/productos/schoco', true),
  (128, 'Galletas Kremali', 'paquete de 70 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 1.11, 0.00, 'tudespensa25/productos/kremali', true),
  (125, 'Waffer de Vainilla, fresa y chocolate', 'paquete de 140 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 1.50, 0.00, 'tudespensa25/productos/waferfresa', true),
  (126, 'Caja de sorbeticos  de Vainilla', 'Caja de 12 paquetes de 40  gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 7.50, 0.00, 'tudespensa25/productos/sorbetico', true),
  (110, 'Galletas Snack Crackers', 'Caja de 3 paquetes 189 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 2.50, 0.00, 'tudespensa25/productos/snackcrackers', true),
  (111, 'Donas de Fresa 🍓', 'Caja de 24 unidades', (select id from categorias where nombre = 'Alimentos/Del Confi'), 7.50, 0.00, 'tudespensa25/productos/donutfresa', true),
  (70, 'Bolita de chocolate', 'bolsa de 500 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 3.20, 0.00, 'tudespensa25/productos/bolitas', false),
  (71, 'Best Chocolate', 'Pomo de conitos 595 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 3.20, 0.00, 'tudespensa25/productos/conito', false),
  (72, 'Galletas Saltine Nezka', 'Cajita de 454 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 3.50, 0.00, 'tudespensa25/productos/saltine', false),
  (73, 'Galletas Soda', 'Paquete de 8 uds', (select id from categorias where nombre = 'Alimentos/Del Confi'), 3.20, 0.00, 'tudespensa25/productos/soda', false),
  (20012, 'Combo Para Mamá 1', 'Incluye 2 Bottelas de 1 L de aceite, 800 gr de Pasta de  Tomate, 5 spaguetis, 1 Garbanzo Goya, Bolsa de 5 lb de Frijol Negro,1 Mayonesa Celorio, Bolsa de 1 kg de Leche en Polvo, 2 Latas de Leche Condensada', (select id from categorias where nombre = 'Combos Temporales'), 41.99, 0.00, 'tudespensa25/productos/combo1m', false),
  (30026, 'Combo De Granos', 'Incluye 11 Lb de Arroz Brasileño, 5 Lb de Frijol Negro .', (select id from categorias where nombre = 'Combos en oferta'), 16.50, 0.00, 'tudespensa25/productos/combo2', false),
  (20038, 'Combo Fresa 🍓', 'Incluye Caja de 24 donas de fresa, 1 cubeta de 4 L de yogurt probiótico de Fresa', (select id from categorias where nombre = 'Combos en oferta'), 18.50, 0.00, 'tudespensa25/productos/comboyogurt', false),
  (20044, 'Combo Apis+ Pollo', 'Incluye 1 bolsa sellada al vacío de 3lb de pollo ahumado + 1 Tomate frito Español Apis', (select id from categorias where nombre = 'Combos Temporales'), 8.50, 0.00, 'tudespensa25/productos/polloapis', false),
  (20055, 'Combo Granos Plus', 'Incluye 50 lb de Arroz Brasileño, 10 lb de Frijol Negro, 8 lb de Azúcar Blanca.', (select id from categorias where nombre = 'Combos en oferta'), 70.00, 0.00, 'tudespensa25/productos/combo4m', false),
  (20062, 'Combo Para Mamá 5', 'Incluye 6 compotas, 6 latas de jugo multifrutas, 1 mantequilla de maní, 2 Tubos de galleta María, 3 Papitas Classic Mixtas.', (select id from categorias where nombre = 'Combos en oferta'), 20.00, 0.00, 'tudespensa25/productos/combo5m', false),
  (20072, 'Combo Para Mamá 6', 'Incluye 1 Pomo de Ajo triturado badia, 1 zumo de limón badia , 1 zumo de naranja badia, 2 botellas de aceite de 1 L, caja de 20 sazones Tropical.', (select id from categorias where nombre = 'Combos Temporales'), 17.99, 0.00, 'tudespensa25/productos/combo6m', false),
  (20082, 'Combo Para Mamá 7', 'Incluye 5 paquetes de spahgetti, 1 lata de 800 gr de pasta de tomate, 1 pomo de queso parmesano, 1 mayonesa celorio de 500 gr', (select id from categorias where nombre = 'Combos Temporales'), 20.99, 0.00, 'tudespensa25/productos/combo7m', false),
  (20092, 'Combo Para Mamá 8', 'Incluye 1 paquete de chicharos verde de 16 oz, 1 paquete de alubias de 16 oz, 1 paquete de frijol negro de 1 kg, 1 paquete de garbanzos de 16 oz, 1 bolsa de 1kg de frijol colorado', (select id from categorias where nombre = 'Combos Temporales'), 9.20, 0.00, 'tudespensa25/productos/combo8m', false),
  (20102, 'Combo Para Mamá 9', 'Incluye 1 paquete galletas marias (bolsa de 12 paqueticos, 6 Jugos de pera de 200 ml, 6 compotas, 3 papitas clasicc)', (select id from categorias where nombre = 'Combos Temporales'), 13.99, 0.00, 'tudespensa25/productos/combo9m', false);

commit;