begin;

insert into productos (id, nombre, descripcion, categoria_id, precio_usd, descuento_pct, imagen_id, reciente) values
  (108, 'Refresco', 'Lata 330 ml', (select id from categorias where nombre = 'Alimentos/Líquidos'), 0.55, 0.00, 'tudespensa25/productos/cintranaranja', true),
  (202, 'Refresco Zuko', 'Caja de 8 sobres', (select id from categorias where nombre = 'Alimentos/Líquidos'), 3.60, 0.00, 'tudespensa25/productos/zuko', false),
  (29, 'Refresco', 'Pomo de 2 Lt', (select id from categorias where nombre = 'Alimentos/Líquidos'), 1.90, 0.00, 'tudespensa25/productos/1-5lt', false),
  (30, 'Café', 'Paquete de 250 gr', (select id from categorias where nombre = 'Alimentos/Líquidos'), 5.90, 0.00, 'tudespensa25/productos/cafearoma', false),
  (76, 'Café Expreso', 'Paquete de 250 gr', (select id from categorias where nombre = 'Alimentos/Líquidos'), 5.60, 0.00, 'tudespensa25/productos/cafenezka', false),
  (130, 'Café La Llave', 'Paquete de 283 gr', (select id from categorias where nombre = 'Alimentos/Líquidos'), 6.90, 0.00, 'tudespensa25/productos/lallave', false),
  (78, 'Ajo Finamente picado Badia', 'Pomo de 8 OZ', (select id from categorias where nombre = 'Aderezo y condimentos'), 2.60, 0.00, 'tudespensa25/productos/ajobadia', false),
  (127, 'Maíz dulce en granos', 'lata de 445 gr', (select id from categorias where nombre = 'Enlatados y conservas'), 1.70, 0.00, 'tudespensa25/productos/maizdulce', true),
  (80, 'Jugo de Naranja Agria Badia', 'Pomo de 10 OZ', (select id from categorias where nombre = 'Aderezo y condimentos'), 2.60, 0.00, 'tudespensa25/productos/naranjabadia', false),
  (81, 'ketchup kurtz', 'Pomo de 10 OZ', (select id from categorias where nombre = 'Aderezo y condimentos'), 2.95, 0.00, 'tudespensa25/productos/ketchupkurtz', false),
  (82, 'Chicharos verdes Del Monte', 'Bolsa de 16 OZ', (select id from categorias where nombre = 'Granos'), 1.95, 0.00, 'tudespensa25/productos/chicharodelmonte', false),
  (83, 'Alubias Del Monte', 'Bolsa de 16 OZ', (select id from categorias where nombre = 'Granos'), 2.40, 0.00, 'tudespensa25/productos/alubiasdelmonte', false),
  (84, 'Lentejas Goya', 'Bolsa de 14 OZ', (select id from categorias where nombre = 'Granos'), 2.40, 0.00, 'tudespensa25/productos/lentejasgoya', false),
  (85, 'Garbanzos Goya', 'Bolsa de 14 OZ', (select id from categorias where nombre = 'Granos'), 2.95, 0.00, 'tudespensa25/productos/garbanzosgoya', false),
  (86, 'Mantequilla de Maní', 'Pomo de 16 OZ', (select id from categorias where nombre = 'Alimentos/Otros'), 4.95, 0.00, 'tudespensa25/productos/mantequillamani', true),
  (87, 'Botella de Aceite', 'Botella  de 1 L', (select id from categorias where nombre = 'Aderezo y condimentos'), 3.20, 0.00, 'tudespensa25/productos/aceite', true),
  (147, 'Botella de Aceite', 'Botella  de 500 ml', (select id from categorias where nombre = 'Aderezo y condimentos'), 1.60, 0.00, 'tudespensa25/productos/aceite500', true),
  (88, 'Compota Babe', 'Pomito de 4 Oz', (select id from categorias where nombre = 'Enlatados y conservas'), 0.90, 0.00, 'tudespensa25/productos/compota', false),
  (89, 'Vinagre Goya', 'Pomo de 16 Oz', (select id from categorias where nombre = 'Aderezo y condimentos'), 1.95, 0.00, 'tudespensa25/productos/vinagregoya', true),
  (90, 'Sazón Tropical Badia', 'Cajita de 20 Uds Ideal para carnes', (select id from categorias where nombre = 'Aderezo y condimentos'), 3.40, 0.00, 'tudespensa25/productos/tropicalcarnes', false),
  (91, 'Sazón Tropical Badia.', 'Cajita de 20 Uds Ideal para Arroces y Cardos', (select id from categorias where nombre = 'Aderezo y condimentos'), 3.40, 0.00, 'tudespensa25/productos/tropicalarroz', false),
  (31, 'pasta de tomate Sabrosísimo', 'Pasta doble concentrado 800 gr', (select id from categorias where nombre = 'Enlatados y conservas'), 3.50, 0.00, 'tudespensa25/productos/800gr', false),
  (112, 'Pure de Tomate Sara', 'Pure de Tomate 400 gr', (select id from categorias where nombre = 'Enlatados y conservas'), 1.65, 0.00, 'tudespensa25/productos/puresara', true),
  (115, 'Tomate Frito Apis', 'Caja de  400 gr', (select id from categorias where nombre = 'Enlatados y conservas'), 2.20, 0.00, 'tudespensa25/productos/tomatefrito', true),
  (113, 'Pure de Papas Deshidratadas', 'Pure de Papas 390 gr para 18 porciones', (select id from categorias where nombre = 'Productos mixtos'), 6.40, 0.00, 'tudespensa25/productos/purepapa', true),
  (32, 'Pomo de Garbanzos Cocidos', 'Pomo de 540 gr', (select id from categorias where nombre = 'Enlatados y conservas'), 2.20, 0.00, 'tudespensa25/productos/garbanzos', false),
  (33, 'Mayonesa Celorio', 'Pomo de 500 gr', (select id from categorias where nombre = 'Alimentos/Otros'), 4.20, 0.00, 'tudespensa25/productos/mayonesa', true),
  (109, 'Pomo de Aceitunas', 'Pomo de 290 gr', (select id from categorias where nombre = 'Enlatados y conservas'), 3.00, 0.00, 'tudespensa25/productos/aceituna290gr', true),
  (34, 'Sazón Completo Nezka', 'Pomo de 250 gr', (select id from categorias where nombre = 'Aderezo y condimentos'), 4.20, 0.00, 'tudespensa25/productos/sazonmixto', false),
  (35, 'Spaguetis', 'Bolsa de 500 gr', (select id from categorias where nombre = 'Productos mixtos'), 1.55, 0.00, 'tudespensa25/productos/spaguetis', false),
  (36, 'Codito', 'Bolsa de 500 gr', (select id from categorias where nombre = 'Productos mixtos'), 1.55, 0.00, 'tudespensa25/productos/codito', false),
  (37, 'Azucar Blanca', 'bolsa de 1 kg', (select id from categorias where nombre = 'Granos'), 2.00, 0.00, 'tudespensa25/productos/azucar1kg', false),
  (38, 'Frijol Negro', 'bolsa de 5 Lb', (select id from categorias where nombre = 'Granos'), 8.00, 0.00, 'tudespensa25/productos/frijol5lb', false),
  (39, 'Frijol Negro', 'bolsa de 1 kg', (select id from categorias where nombre = 'Granos'), 3.20, 0.00, 'tudespensa25/productos/frijol1kg', false),
  (136, 'Frijol Negro', 'bolsa de 500 gr', (select id from categorias where nombre = 'Granos'), 1.80, 0.00, 'tudespensa25/productos/frijol1kg', false),
  (40, 'Frijol Colorado', 'bolsa de 5 Lb', (select id from categorias where nombre = 'Granos'), 8.00, 0.00, 'tudespensa25/productos/colorados5lb', false),
  (41, 'Sal Iodada', 'bolsa de 1 kg', (select id from categorias where nombre = 'Granos'), 1.20, 0.00, 'tudespensa25/productos/sal', false),
  (42, 'Arroz Brasileño', 'bolsa de 1 kg', (select id from categorias where nombre = 'Granos'), 2.20, 0.00, 'tudespensa25/productos/arroz1kg', false),
  (43, 'Fideos', 'bolsa de 500 gr', (select id from categorias where nombre = 'Productos mixtos'), 1.80, 0.00, 'tudespensa25/productos/fideos', false),
  (401, 'Sopa Intantanea', 'Sabor pollo sobre 75 gr', (select id from categorias where nombre = 'Productos mixtos'), 0.70, 0.00, 'tudespensa25/productos/sopa', false);

commit;