begin;

insert into productos (id, nombre, descripcion, categoria_id, precio_usd, descuento_pct, imagen_id, reciente) values
  (44, 'Zumo de Limón', 'Botella de 1l', (select id from categorias where nombre = 'Aderezo y condimentos'), 2.25, 0.00, 'tudespensa25/productos/zumo', false),
  (45, 'Cartón de huevos', '30 uds frescos 100 % orgánicos', (select id from categorias where nombre = 'Productos mixtos'), 9.40, 0.00, 'tudespensa25/productos/huevo', false),
  (201, 'Gelatina', 'Bolsa de gelatina 75 gr', (select id from categorias where nombre = 'Alimentos/Del Confi'), 1.10, 20.00, 'tudespensa25/productos/gelatina', false),
  (74, 'Mayonesa Nezka', 'pomo de 500  gr', (select id from categorias where nombre = 'Alimentos/Otros'), 3.20, 0.00, 'tudespensa25/productos/mayonezka', false),
  (402, 'Queso Parmesano', 'Pomo de 8 Oz', (select id from categorias where nombre = 'Alimentos/Lácteos'), 6.20, 0.00, 'tudespensa25/productos/quesoparmesano', true),
  (102, 'Yogurt Probiótico', 'Cubeta de 4L', (select id from categorias where nombre = 'Alimentos/Lácteos'), 13.50, 0.00, 'tudespensa25/productos/yogurt', false),
  (151, 'Yogurt Probiótico', 'Pomo de 1L', (select id from categorias where nombre = 'Alimentos/Lácteos'), 3.10, 0.00, 'tudespensa25/productos/yogurt1l', false),
  (152, 'Yogurt Probiótico', 'Vasito de 180 ml', (select id from categorias where nombre = 'Alimentos/Lácteos'), 0.60, 0.00, 'tudespensa25/productos/yogurtvasito', false),
  (135, 'Yogurt de Vasito De Fresa', 'Pack de 4 Vasitos de 125 gr', (select id from categorias where nombre = 'Alimentos/Lácteos'), 2.65, 0.00, 'tudespensa25/productos/yoqo', false),
  (403, 'Queso Gouda Aleman', 'Porción de 1 Kg sellado al vacio', (select id from categorias where nombre = 'Alimentos/Lácteos'), 13.50, 0.00, 'tudespensa25/productos/gouda', false),
  (404, 'Helado', 'Cubeta de 3L', (select id from categorias where nombre = 'Alimentos/Lácteos'), 12.00, 10.00, 'tudespensa25/productos/helado', false),
  (100, 'Leche en Polvo', 'Bolsa de 1 kg', (select id from categorias where nombre = 'Alimentos/Lácteos'), 8.50, 0.00, 'tudespensa25/productos/lechepolvomu', false),
  (46, 'Leche Condensada', 'Lata con abre fácil', (select id from categorias where nombre = 'Alimentos/Lácteos'), 1.90, 0.00, 'tudespensa25/productos/condensada', false),
  (47, 'Ajo', 'Bolsa de 10 cabezas', (select id from categorias where nombre = 'Alimentos/Del Agro'), 4.70, 0.00, 'tudespensa25/productos/ajo', false),
  (48, 'Malanga', 'bolsa de 5 lb', (select id from categorias where nombre = 'Alimentos/Del Agro'), 3.00, 0.00, 'tudespensa25/productos/malanga', false),
  (49, 'cebolla', 'bolsa de 2.5 lb aproximadamente', (select id from categorias where nombre = 'Alimentos/Del Agro'), 3.30, 0.00, 'tudespensa25/productos/cebolla', false),
  (50, 'Papas frescas', 'Bolsa de 5 lb frescas', (select id from categorias where nombre = 'Alimentos/Del Agro'), 8.40, 55.00, 'tudespensa25/productos/papas', false),
  (51, 'Col', 'bolsa con 1 unidad sellada', (select id from categorias where nombre = 'Alimentos/Del Agro'), 1.70, 0.00, null, false),
  (52, 'Boniato', 'bolsa de 5 lb', (select id from categorias where nombre = 'Alimentos/Del Agro'), 2.40, 0.00, 'tudespensa25/productos/boniato', false),
  (53, 'Frazada de limpiar suelo', '2 unidades', (select id from categorias where nombre = 'Del Hogar'), 2.40, 0.00, 'tudespensa25/productos/frazada', false),
  (116, 'Detergente Liquido Lavaloza', 'Pomo de 500 ml', (select id from categorias where nombre = 'Del Hogar'), 2.60, 0.00, 'tudespensa25/productos/lavaloza', true),
  (117, 'Detergente Liquido STB', 'Bolsa de 1 L', (select id from categorias where nombre = 'Del Hogar'), 3.20, 0.00, 'tudespensa25/productos/stbliquido', true),
  (55, 'Detergente polvo Multiuso', 'bolsa de 1 Kg', (select id from categorias where nombre = 'Del Hogar'), 2.60, 0.00, 'tudespensa25/productos/detergente', false),
  (56, 'Jabón De Olor', 'por unidades de 100 gr', (select id from categorias where nombre = 'Del Hogar'), 0.90, 0.00, 'tudespensa25/productos/jabon', false),
  (57, 'Papel Higienico', 'bolsa con 4 unidad sellada', (select id from categorias where nombre = 'Del Hogar'), 2.20, 0.00, 'tudespensa25/productos/papel', false),
  (58, 'Perlas de olor para ropa', 'frasco de 200 gr', (select id from categorias where nombre = 'Del Hogar'), 3.50, 0.00, 'tudespensa25/productos/perlas', false),
  (59, 'Suavizante para ropa', 'Pomo de 1 lt', (select id from categorias where nombre = 'Del Hogar'), 6.00, 0.00, 'tudespensa25/productos/suavizante', false),
  (60, 'Toallitas humedas multiuso premiun', 'Paquete de 120 udst', (select id from categorias where nombre = 'Del Hogar'), 3.80, 0.00, 'tudespensa25/productos/toallas', false),
  (61, 'Pastillas de inodoro', '4 uds', (select id from categorias where nombre = 'Del Hogar'), 2.40, 0.00, 'tudespensa25/productos/pastillas', false),
  (62, 'Ventilador de pedestal', 'Ventilador tipo ciclón Milexus', (select id from categorias where nombre = 'De Electrodomésticos'), 60.00, 0.00, 'tudespensa25/productos/ventilador', false),
  (94, 'Cajas de tv Hd', 'Caja descodificadora Hd', (select id from categorias where nombre = 'De Electrodomésticos'), 65.00, 0.00, 'tudespensa25/productos/cajita', false),
  (95, 'Olla reina Milexus', 'Olla reina de 6L Milexus', (select id from categorias where nombre = 'De Electrodomésticos'), 100.00, 0.00, 'tudespensa25/productos/reina', false),
  (96, 'Olla Arrocera', 'Olla arrocera de 1,8 l Milexus', (select id from categorias where nombre = 'De Electrodomésticos'), 60.00, 0.00, 'tudespensa25/productos/arrocera', false),
  (97, 'Freidora de aire', 'Olla freidora de aire de 4 l', (select id from categorias where nombre = 'De Electrodomésticos'), 100.00, 0.00, 'tudespensa25/productos/freidora', false),
  (114, 'Fogon de 3 quemadores', 'Fogon milexus de 3 quemadores', (select id from categorias where nombre = 'De Electrodomésticos'), 75.00, 0.00, 'tudespensa25/productos/fogon', false),
  (98, 'Ventilador de pared', 'Ventilador de 18 pulgadas de pared', (select id from categorias where nombre = 'De Electrodomésticos'), 75.00, 0.00, 'tudespensa25/productos/ventiladorpared', false),
  (99, 'Fogon Infrarrojo', 'Fogon Infrarrojo 1300 W', (select id from categorias where nombre = 'De Electrodomésticos'), 100.00, 0.00, 'tudespensa25/productos/fogoninfra', false),
  (103, 'Microwave Premier 20 Litro', 'Microwave Premier 20 Litro', (select id from categorias where nombre = 'De Electrodomésticos'), 160.00, 0.00, 'tudespensa25/productos/microwave', false),
  (104, 'Lavadora automática 8 L', 'Lavadora automatica 8 L', (select id from categorias where nombre = 'De Electrodomésticos'), 400.00, 0.00, 'tudespensa25/productos/automatica', false),
  (105, 'Lavadora Semiautomática Milexus 7 L', 'Lavadora semiautomatica 7 L', (select id from categorias where nombre = 'De Electrodomésticos'), 320.00, 0.00, 'tudespensa25/productos/semiautomatica7', false);

commit;